name: Window 10

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download latest ngrok
      run: |
        $ngrokUrl = "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip"
        Invoke-WebRequest $ngrokUrl -OutFile ngrok.zip
        if (Test-Path ngrok.zip) {
          Write-Host "Download successful"
        } else {
          Write-Host "Download failed"
          exit 1
        }
    
    - name: Extract ngrok
      run: Expand-Archive -Path ngrok.zip -DestinationPath . -Force
    
    - name: Check ngrok version
      run: .\ngrok.exe version
    
    - name: Auth
      run: .\ngrok.exe config add-authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    
    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    
    - name: Set user password
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "@cyb3rking" -Force)
    
    - name: Create Tunnel
      run: .\ngrok.exe tcp 3389 --log stdout
